config:
  name: django-template-lxc
  template: download
  options:
    - '--dist'
    - 'alpine'
    - '--release'
    - '3.18'
    - '--arch'
    - 'amd64'
  devices:
    eth0:
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  limits:
    memory: 2GB
    cpu: 2
